# 端口
server:
  port: 8011

spring:
  profiles:
    active: dev
  redis:
    # Redis服务器连接端口
    port: 6379
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接密码（默认为空）
    password:
    lettuce:
      pool:
        max-wait: 3s
#  关闭cglib代理方式，因为springboot2.x 中默认设置为cglib方式进行代理，且启动类上注解@EnableAspectJAutoProxy默认为false
#  表示无法使用jdk代理，则需要再配置文件中添加配置进行修改
#  aop:
#    proxy-target-class: false
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: root
#    password: root
#    virtual-host: /demo