# 端口
server:
  port: 7031

spring:
  profiles:
    active: dev
  redis:
    # Redis服务器连接端口
    port: 6379
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接密码（默认为空）
    password:
    lettuce:
      pool:
        max-wait: 3s
#  aop:
#    proxy-target-class: false
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: root
#    password: root
#    virtual-host: /demo